GET  http://localhost:8899/api/shutdown
###
GET http://localhost:8899/api/xxx
###

# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
 #"identity" : "andy4@mail.com",
 "identity": "0861864848",
 "firstName" : "someone",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###


GET http://localhost:8899/api/auth
###
GET http://localhost:8899/api/post 
###

# Login api
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
 #"identity" : "andy4@mail.com",
 "identity" : "0861864848",
 "password" : "123456"
}

###

# Get me 
GET  http://localhost:8899/api/auth/me
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImlhdCI6MTc2MTc5NjkxNywiZXhwIjoxNzYzMDkyOTE3fQ.jXOMforXs2wGZ3m-a0MEKrwuvtFV3HbP-ss82TWEo3A

###